springdoc:
  swagger-ui:
    enabled: true
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zcunsoft.accesslog.api.controllers
server:
  port: 8089
spring:
  application.name: accesslog-api
  datasource:
    clickhouse:
      jdbc-url: jdbc:clickhouse://localhost:8123/default
      username: default
      password:
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      connection-timeout: 20000
      maximum-pool-size: 5
logging:
  file:
    path: log
accesslogapi:
  access-control-allow-origin: "*"
  project-name: accesslog
